start node bot1.js
start node bot2.js
start node bot3.js
start node bot4.js
start node bot5.js
start node bot6.js
start node bot7.js
start node bot8.js
start node bot9.js
start node bot10.js
start node bot11.js
start node bot12.js
start node bot13.js
start node bot14.js
start node bot15.js
start node bot16.js
start node bot17.js
start node bot18.js
start node bot19.js
start node bot20.js
start node bot21.js
start node bot22.js
start node bot23.js
start node bot24.js
start node bot25.js
start node bot26.js
start node bot27.js
start node bot28.js
start node bot29.js
start node bot30.js
start node bot31.js
start node bot32.js
start node bot33.js
start node bot34.js
start node bot35.js
start node bot36.js
start node bot37.js
start node bot38.js
start node bot39.js
start node bot40.js